version: '1.0.0'

networks:
  datax:
    driver: bridge

volumes:
  web:
    driver: local
  api:
    driver: local  

services:

  web:
    build:
      context: ./frontend
    volumes:
      - ${PATH_DATA}:/data/data
    ports:
      - ${DATAX_WEB_PORT}:80
    networks:
      - datax

  api:
    build:
      context: ./backend
    volumes:
      - ${PATH_DATA}:/data/data
    ports:
      - ${DATAX_API_PORT}:80
    networks:
      - datax  

